config/routes.rb
DraftTool::Application.routes.draw do
  root :to => 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :team_settings

  post 'players/:id/toggle_selected' => 'players#toggle_selected'
  post 'players/:id/toggle_removed' => 'players#toggle_removed'
  post 'players/:id/toggle_marked' => 'players#toggle_marked'
  get "/set_session_sort" => "teams#set_session_sort"
  get "/set_session_sort" => "teams#set_session_sort"
  get '/teams/:id/update_stats' => 'teams#update_player_stats'

  devise_for :users
  resources :teams
  ActiveAdmin.routes(self)

end

def toggle_selected_path(player)
  "/players/#{player.id}/toggle_selected"
end

def toggle_removed_path(player)
  "/players/#{player.id}/toggle_removed"
end

def toggle_marked_path(player)
  "/players/#{player.id}/toggle_marked"
end

def set_session_sort_path
  "/set_session_sort"
end

def update_team_stats_path(team)
  "/teams/#{team.id}/update_stats"
end

app/models/team_setting.rb
class TeamSetting < ActiveRecord::Base
  belongs_to :team
  attr_accessible :attempts, :completions, :interceptions, :passing_touchdowns, :passing_yards, :receiving_touchdowns, :receiving_yards, :receptions, :rushes, :rushing_touchdowns, :rushing_yards, :qb_points, :rb1_points, :rb2_points, :wr1_points, :wr2_points, :flex_points, :te_points, :k_points, :dst_points

  before_save :set_ideal_total

  def set_ideal_total
    self.total_points = calculate_ideal_total
  end

  def calculate_ideal_total
    [qb_points,
      rb1_points,
      rb2_points,
      wr1_points,
      wr2_points,
      flex_points,
      te_points,
      k_points,
      dst_points].reduce(:+)
  end
end

app/controllers/team_settings_controller.rb
class TeamSettingsController < InheritedResources::Base
end

app/helpers/team_settings_helper.rb
module TeamSettingsHelper
end

app/views/team_settings/_form.html.erb
<div class="row">
  <%= form_for(@team_setting, :html => { :class => "edit_team_setting form-horizontal" }) do |f| %>
    <% if @team_setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@team_setting.errors.count, "error") %> prohibited this team_setting from being saved:</h2>

        <ul>
          <% @team_setting.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <legend>Scoring</legend>

    <div class="form-group">
      <%= f.label :completions, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :completions, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :attempts, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :attempts, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :passing_yards, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :passing_yards, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :passing_touchdowns, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :passing_touchdowns, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :interceptions, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :interceptions, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :rushes, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :rushes, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :rushing_yards, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :rushing_yards, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :rushing_touchdowns, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :rushing_touchdowns, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :receptions, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :receptions, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :receiving_yards, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :receiving_yards, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :receiving_touchdowns, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :receiving_touchdowns, :class => "form-control" %><br />
      </div>
    </div>

    <legend>Ideal PPG</legend>

    <div class="form-group">
      <%= f.label :qb_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :qb_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :rb1_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :rb1_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :rb2_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :rb2_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :wr1_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :wr1_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :wr2_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :wr2_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :flex_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :flex_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :te_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :te_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :k_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :k_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= f.label :dst_points, :class => "col-md-2 control-label" %>
      <div class="col-md-4 col-md-offset-2">
        <%= f.text_field :dst_points, :class => "form-control" %><br />
      </div>
    </div>

    <div class="form-group">
      <%= link_to "Cancel", @team_setting.team, :class => "btn btn-default" %>
      <%= f.submit "Submit", :class => "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/team_settings/edit.html.erb
<div class="center">
  <div class="page-header">
    <h1>Edit League Settings</h1>
    <small><%= link_to 'Back', @team_setting.team %></small>
  </div>

  <div class="hero-unit">
    <%= render 'form' %>
  </div>
</div>

app/views/team_settings/index.html.erb
<h1>Listing team_settings</h1>

<table>
  <tr>
    <th>Team</th>
    <th>Completions</th>
    <th>Attempts</th>
    <th>Passing yards</th>
    <th>Passing touchdowns</th>
    <th>Interceptions</th>
    <th>Rushes</th>
    <th>Rushing yards</th>
    <th>Rushing touchdowns</th>
    <th>Receptions</th>
    <th>Receiving yards</th>
    <th>Receiving touchdowns</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_settings.each do |team_setting| %>
  <tr>
    <td><%= team_setting.team %></td>
    <td><%= team_setting.completions %></td>
    <td><%= team_setting.attempts %></td>
    <td><%= team_setting.passing_yards %></td>
    <td><%= team_setting.passing_touchdowns %></td>
    <td><%= team_setting.interceptions %></td>
    <td><%= team_setting.rushes %></td>
    <td><%= team_setting.rushing_yards %></td>
    <td><%= team_setting.rushing_touchdowns %></td>
    <td><%= team_setting.receptions %></td>
    <td><%= team_setting.receiving_yards %></td>
    <td><%= team_setting.receiving_touchdowns %></td>
    <td><%= link_to 'Show', team_setting %></td>
    <td><%= link_to 'Edit', edit_team_setting_path(team_setting) %></td>
    <td><%= link_to 'Destroy', team_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Team setting', new_team_setting_path %>

app/views/team_settings/new.html.erb
<h1>New team_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', team_settings_path %>

app/views/team_settings/show.html.erb
<div class="page-header">
  <h1>League Settings</h1>
  <small><%= link_to 'Edit League Settings', edit_team_setting_path(@team_setting) %></small> |
  <small><%= link_to "Back to #{@team_setting.team.name}", team_path(@team_setting.team) %></small>
</div>

<div class="row-fluid">
  <div class="span5">

    <h3>Scoring</h3>

    <p>
    <b>Completions:</b>
    <%= @team_setting.completions %>
    </p>

    <p>
    <b>Attempts:</b>
    <%= @team_setting.attempts %>
    </p>

    <p>
    <b>Passing yards:</b>
    <%= @team_setting.passing_yards %>
    </p>

    <p>
    <b>Passing touchdowns:</b>
    <%= @team_setting.passing_touchdowns %>
    </p>

    <p>
    <b>Interceptions:</b>
    <%= @team_setting.interceptions %>
    </p>

    <p>
    <b>Rushes:</b>
    <%= @team_setting.rushes %>
    </p>

    <p>
    <b>Rushing yards:</b>
    <%= @team_setting.rushing_yards %>
    </p>

    <p>
    <b>Rushing touchdowns:</b>
    <%= @team_setting.rushing_touchdowns %>
    </p>

    <p>
    <b>Receptions:</b>
    <%= @team_setting.receptions %>
    </p>

    <p>
    <b>Receiving yards:</b>
    <%= @team_setting.receiving_yards %>
    </p>

    <p>
    <b>Receiving touchdowns:</b>
    <%= @team_setting.receiving_touchdowns %>
    </p>
  </div>

  <div class="span5">
    <h3>Ideal PPG</h3>

    <p>
    <b>QB Points:</b>
    <%= @team_setting.qb_points %>
    </p>
    <p>
    <b>RB1 Points:</b>
    <%= @team_setting.rb1_points %>
    </p>
    <p>
    <b>RB2 Points:</b>
    <%= @team_setting.rb2_points %>
    </p>
    <p>
    <b>WR1 Points:</b>
    <%= @team_setting.wr1_points %>
    </p>
    <p>
    <b>WR2 Points:</b>
    <%= @team_setting.wr2_points %>
    </p>
    <p>
    <b>Flex Points:</b>
    <%= @team_setting.flex_points %>
    </p>
    <p>
    <b>TE Points:</b>
    <%= @team_setting.te_points %>
    </p>
    <p>
    <b>K Points:</b>
    <%= @team_setting.k_points %>
    </p>
    <p>
    <b>DST Points:</b>
    <%= @team_setting.dst_points %>
    </p>
    <p>
    <b>Total Points:</b>
    <%= @team_setting.total_points %>
    </p>
  </div>