config/routes.rb
DraftTool::Application.routes.draw do
  root :to => 'home#index'
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :team_settings

  post 'players/:id/toggle_selected' => 'players#toggle_selected'
  post 'players/:id/toggle_removed' => 'players#toggle_removed'
  post 'players/:id/toggle_marked' => 'players#toggle_marked'
  get "/set_session_sort" => "teams#set_session_sort"
  get "/set_session_sort" => "teams#set_session_sort"
  get '/teams/:id/update_stats' => 'teams#update_player_stats'

  devise_for :users
  resources :teams
  ActiveAdmin.routes(self)

end

def toggle_selected_path(player)
  "/players/#{player.id}/toggle_selected"
end

def toggle_removed_path(player)
  "/players/#{player.id}/toggle_removed"
end

def toggle_marked_path(player)
  "/players/#{player.id}/toggle_marked"
end

def set_session_sort_path
  "/set_session_sort"
end

def update_team_stats_path(team)
  "/teams/#{team.id}/update_stats"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DraftTool</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body style="padding-top: 70px;">
    <div class="navbar navbar-default navbar-fixed-top" style="border-radius:0px; -webkit-border-radius:0px; -moz-border-radius:0px;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-responsive-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Draft Tool</a>
        </div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="divider-vertical"></li>
            <% if user_signed_in? %>
              <li>
                <%= link_to "My Teams", teams_path %>
              </li>
              <li class="divider-vertical"></li>
              <li>
                <%= link_to "Research", "http://fftrends.appspot.com/" %>
              </li>
              <li class="divider-vertical"></li>
              <li>
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              </li>
            <% else %>
              <li>
                <%= link_to "Research", "http://fftrends.appspot.com/" %>
              </li>
              <li class="divider-vertical"></li>
              <li>
                <%= link_to "Sign in", new_user_session_path %>
              </li>
            <% end %>
            <li class="divider-vertical"></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if notice %>
        <br>
        <p class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <br>
        <p class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= alert %>
        </p>
      <% end %>

      <br>

      <%= yield %>
    </div>

  </body>
</html>